snapshot: &snapshot
  working_directory: ~/repo
  steps:
    - checkout
    - run:
        name: Install build dependencies
        command: |
          apt-get update -qq
          apt-get install -y dh-make git lsb-release
    - run:
        name: Create changelog
        command: |
          CODENAME=$(lsb_release --codename --short)
          RELEASE=$(lsb_release --release --short)
          ./changelog.sh firstboot-it4smart ${CODENAME} deb${RELEASE} > debian/changelog

    - run:
        name: Create source archive
        command: |
          export GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          export GIT_COMMIT=${CIRCLE_SHA1:0:7}
          mkdir -p ~/repo/firstboot-it4smart-${GIT_TAG//v}+git-${GIT_COMMIT}
          tar -czf /tmp/firstboot-it4smart_${GIT_TAG//v}+git-${GIT_COMMIT}.orig.tar.gz .
          tar -xzf /tmp/firstboot-it4smart_${GIT_TAG//v}+git-${GIT_COMMIT}.orig.tar.gz -C ~/repo/firstboot-it4smart-${GIT_TAG//v}+git-${GIT_COMMIT}

    - run:
        name: Build package
        command: |
          export GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          export GIT_COMMIT=${CIRCLE_SHA1:0:7}
          cd ~/repo/firstboot-it4smart-${GIT_TAG//v}+git-${GIT_COMMIT}
          dpkg-buildpackage -us -uc

    - run: 
        name: Save build
        command: |
          mkdir -p ~/build
          mv ~/repo/*.deb ~/build/
    - store_artifacts:
        path: ~/build
    - persist_to_workspace:
        root: ~/
        paths:
          - build/*

version: 2
jobs:
  build-commit-debian-buster-i386:
    docker:
      - image: i386/debian:buster-slim
    <<: *snapshot

workflows:
  version: 2
  build-snapshot:
    jobs:
      - build-commit-debian-buster-i386:
          filters:
            tags:
              ignore: /.*/